import {
  amber,
  blue,
  bronze,
  brown,
  crimson,
  cyan,
  gold,
  grass,
  gray,
  green,
  indigo,
  iris,
  jade,
  lime,
  mint,
  orange,
  pink,
  plum,
  purple,
  red,
  ruby,
  sky,
  teal,
  tomato,
  violet,
  yellow,
} from '@radix-ui/colors';
import { BadgeProps } from '@radix-ui/themes';

export const radixColorMap: Partial<Record<NonNullable<BadgeProps['color']>, string>> = {
  amber: amber.amber9,
  blue: blue.blue9,
  bronze: bronze.bronze9,
  brown: brown.brown9,
  crimson: crimson.crimson9,
  cyan: cyan.cyan9,
  gold: gold.gold9,
  grass: grass.grass9,
  gray: gray.gray9,
  green: green.green9,
  indigo: indigo.indigo9,
  iris: iris.iris9,
  jade: jade.jade9,
  lime: lime.lime9,
  mint: mint.mint9,
  orange: orange.orange9,
  pink: pink.pink9,
  plum: plum.plum9,
  purple: purple.purple9,
  red: red.red9,
  ruby: ruby.ruby9,
  sky: sky.sky9,
  teal: teal.teal9,
  tomato: tomato.tomato9,
  violet: violet.violet9,
  yellow: yellow.yellow9,
};
